---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Set Global Options
```{r}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading and preprocessing the data
```{r}
unzip("activity.zip")
raw_data <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

#Histogram of the total number of steps taken each day
raw_data$date <- as.Date(raw_data$date, "%Y-%m-%d")
steps_per_day <- aggregate(steps ~ date, raw_data, sum)
qplot(steps_per_day$steps, geom = "histogram", xlab="Number of Steps", ylab="Number of days")

#Mean and median number of steps taken each day
daily_mean <- mean(steps_per_day$steps)
daily_mean
daily_median <-median(steps_per_day$steps)
daily_median
```


## What is the average daily activity pattern?
```{r}
avg_steps_time <- aggregate(steps ~ interval, raw_data, mean)
qplot(interval, steps, data=avg_steps_time, geom="line", xlab="Time Interval", ylab="Average Number of Steps")

#The 5-minute interval that, on average, contains the maximum number of steps
avg_steps_time[which.max(avg_steps_time$steps), 1]
```



## Imputing missing values
```{r}
sum(is.na(raw_data$steps)) #count total number of NAs
new_raw_data <- raw_data  #make a copy of the raw data

#cycle through rows, and if steps has 'na', then replace 'na' with the average value.
for (i in 1:nrow(new_raw_data)) {
      if(is.na(new_raw_data[i,1])) {
            new_raw_data[i,1] <- avg_steps_time[which(avg_steps_time$interval==new_raw_data[i,3]), 2]
      }
}

#draw a histogram of the total number of steps taken each day after missing values are imputed.
new_steps_per_day <- aggregate(steps ~ date, new_raw_data, sum)
qplot(new_steps_per_day$steps, geom = "histogram", xlab="Number of Steps", ylab="Number of days")

#Calculate and report the mean and median total number of steps taken per day.
new_daily_mean <- mean(new_steps_per_day$steps)
new_daily_mean
new_daily_median <- median(new_steps_per_day$steps)
new_daily_median

#Do these values differ from the estimates from the first part of the assignment?
diff_mean <- new_daily_mean - daily_mean  #cacluate the difference in mean
diff_mean  
diff_median <- new_daily_median - daily_median #cacluate the difference in median
diff_median

#What is the impact of imputing missing data on the estimates of the total daily number of steps? - See the plot below for the differece between imputted and orginal data by date.
new_steps_per_day <- aggregate(steps ~ date, new_raw_data, sum)
diff_steps_per_day <- merge(new_steps_per_day, steps_per_day, by.x="date", by.y="date", all=TRUE)
diff_steps_per_day[is.na(diff_steps_per_day)] <- 0
diff_steps_per_day <- diff_steps_per_day %>% mutate(diff = steps.x - steps.y)
ggplot(diff_steps_per_day, aes(date, diff)) + geom_point() + labs(y="imputed - orginal")
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
#create a factor column
weekends <- c("Saturday", "Sunday")
new_raw_data <- new_raw_data %>% mutate(day = weekdays(date))
new_raw_data$factor <- as.factor(ifelse(new_raw_data$day %in% weekends, "weekend", "weekday"))

#plot results
weekend_data <- aggregate(steps ~ interval + factor, new_raw_data, mean)
ggplot(weekend_data, aes(interval, steps)) + geom_line() + facet_wrap(~factor, ncol=1, nrow=2)

```

